### ISSUE TITLE
Progression of multi screen layout

### ISSUE THREAD

**Issue by johnagl** [ubclaunchpad/life-at-ubc#117]
Users are currently able to click to any step on the progression (Home, Courses, Restrictions, Labs etc..). Is this the intended design? Or should users have to select courses first before being able to click into labs ? If we want to restrict the progression (ie: users must do step 1 before step 2) I was thinking future steps could be initially greyed out. 

![progression](https://user-images.githubusercontent.com/42220961/106081876-87095f80-60ce-11eb-8460-aae0b8a8e7e9.png)

**Comment by johnagl** [comment]
After discussion in our meeting: 

Future steps in the progression should be greyed out if user hasn't completed the current step.

**Comment by danielchen-pyc** [comment]
I have updated the code (in `daniel` branch) to limit user access to pages that haven't collected enough information. The user needs to finish selecting the required information on the current page to continue to the next page and the state information stored in previous pages will still be preserved. In other words, the user is free to jump back but cannot jump forward without completing the current page. I only modified the code in `HomeReducer.ts`: adding a property in `state` variable called `latestState` and updating it every time the user progresses to a new page. If the user wants to switch states (triggered by the `SWITCHCOMPONENT` action), it checks if the target component index is greater than `latestState`. I will think of a way to grey out the breadcrumb. I tested the code for section 1-3 (Term->Course->Restrictions) but it stops at restriction because I think the code for "restrictions" is not done yet? The restrictions are not stored anywhere, as far as I know. Please let me know if there's anything that can be improved or fixed!

**Comment by johnagl** [comment]
> I have updated the code (in `daniel` branch) to limit user access to pages that haven't collected enough information. The user needs to finish selecting the required information on the current page to continue to the next page and the state information stored in previous pages will still be preserved. In other words, the user is free to jump back but cannot jump forward without completing the current page. I only modified the code in `HomeReducer.ts`: adding a property in `state` variable called `latestState` and updating it every time the user progresses to a new page. If the user wants to switch states (triggered by the `SWITCHCOMPONENT` action), it checks if the target component index is greater than `latestState`. I will think of a way to grey out the breadcrumb. I tested the code for section 1-3 (Term->Course->Restrictions) but it stops at restriction because I think the code for "restrictions" is not done yet? The restrictions are not stored anywhere, as far as I know. Please let me know if there's anything that can be improved or fixed!

Sounds like this is progressing nicely! Restrictions are being calculated in the background - we aren't explicitly setting it's react/redux state anywhere (I think) . It should be fine to not worry about restrictions since the user can have 0 restrictions anyways - yet they should still be able to proceed. So perhaps they should be able to get past restrictions screen as long as they've selected lectures?

**Comment by danielchen-pyc** [comment]
Hello John! I have updated and tested the code to fix the restriction part. The user can jump through restriction without selecting the restrictions. Please have a look!

**Comment by johnagl** [comment]
Took a look at your current code. Good start! There have been a few changes made to the main branch which might require you to change your code a bit (you might also run into merge conflicts) so pull the latest stuff as soon as you can :).

**Comment by johnagl** [comment]
How's this going so far @danielchen-pyc ?

**Comment by danielchen-pyc** [comment]
Hello @johnagl! Sorry for the late response. I was busy studying for the three midterms this week. I have debugged the latestState progression code and pulled the latest commit, it is working normal now including the restriction part. I am still figuring out a way to grey out the breadcrumb. I will let you know what I get in an hour.

**Comment by danielchen-pyc** [comment]
Hello @johnagl! It is done! I have successfully restricted user access when the user haven't added **at least one course**. The breadcrumbs are initially all grayed out except the first one "Home". As the user progress through the website, the breadcrumb will be un-grayed one by one. The user can decide to go back to previous pages without graying breadcrumb again. The code is in `daniel` branch. Let me know if there is anything that I need to modify or improve! Thank you!

**Comment by johnagl** [comment]
@danielchen-pyc Tested your branch out a bit. I have a few comments - request a PR and I'll add them there!

**Comment by johnagl** [comment]
Also, pull the latest code since @yehee pushed some new stuff in recently.
