### ISSUE TITLE
Think about Frontend Implementation

### ISSUE THREAD

**Issue by johnagl** [ubclaunchpad/life-at-ubc#15]
1. Functional (hooks) versus Class Components - we should probably stick to 1 at the beginning so as to be consistent (class)
2. Will we use frameworks such as https://material-ui.com/? 
3. Start thinking about folder structure in the frontend

**Comment by aldy97** [comment]
1. I prefer to use functional components with React hooks over class components. Besides, I have not used class components for a while so I might need some extra time to pick it up especially on life-cycles (componentDidMount, etc). P.S: would that cause any issues if we use mainly functional components combined with class components only if its necessary to do so? 
2. I think we can use UI libs like material-ui and ant design, etc. I am mostly famailiar with antd UI though. Using UI libs greatly saves our time so that we can be more focused on logic layer.
3. Fold structure highly depends on how complex our project is. I cant have a clear vision on how the structure is going to be like at this stage.

**Comment by johnagl** [comment]
@aldy97 It looks like the paradigm in React is shifting towards Functional components and hooks so it's probably a good idea to apply that to our project! I suggested Class components only because it's what most people will recognize from Object Oriented Programming.
