### ISSUE TITLE
Create scheduling algo

### ISSUE THREAD

**Issue by jacksonyuanjx** [ubclaunchpad/life-at-ubc#62]
* we can keep our discussion here - please feel free to add any thoughts you have on how the scheduling should behave :)

## Questions
* should the only criteria for creating schedules be non-overlapping times?
* should we include sections that are full/blocked/waitlist?

**Comment by johnagl** [comment]
To simplify the problem initially, the only criteria should probably be only non-overlapping times. Just include full/block/wait list for now.

**Comment by johnagl** [comment]
The backtracking solution to this https://leetcode.com/problems/combinations/ problem is a good starting point. I was just toying around with this on IntelliJ and testing some stuff out. 

Initially my thoughts are: 
1) Use a backtracking algorithm to generate all combinations of course sections of size k (based on courses selected eg: CPSC 110, CPSC 121, MATH 105), in this case, k = 3.
2) Only take combinations where each course is represented once.
3) Remove duplicates? (I dont think there are actually duplicates with this type of algorithm - but just in case, we should check)

This probably isn't the most efficient way to do it but I don't think we have to worry about efficiency since most worklists for 1 term will be 4-5 courses.
