### ISSUE TITLE
Update on Global State During Course Selection

### ISSUE THREAD

**Issue by aldy97** [ubclaunchpad/life-at-ubc#64]
Today we talked about potential useage of redux thunk. Here are my thoughts on that:
- Rather than we query the database when users are building their selected courses at Courses Selecition stage (unnecessary and inefficient), we should query the db after the overall courses selection has been finalized by them. Thus, we only need to query the db once. 
- The only way we can confirm that the courses selection has been finalized is by determining whether the user has moved forward to the next stage, which is Restriction stage. 
- Following the previous, so we actually query the db when we at Restriction statge NOT in the Courses Selection stage. 
- Since we need to query the db in Restriction stage while the query depends on users' input from previous stage, we should update courses selected in the global state so that these inputs could be accessed from the Restriction stage. So, during the Course Selection stage, we only need to update Redux <b>synchronously</b> following users' addition to courses selected. 
- So I guess it is not necessary to implement Redux-Thunk for now because <b>we do not deal with the situation of real-time course schedule visualization re-render based on user's input</b>.

Here is what I plan to do during Courses Selection Stage:
![image](https://user-images.githubusercontent.com/40585236/98450645-19631e00-20f3-11eb-9d66-fe81b45b7b31.png)
- P.S: async function in useEffect is very tricky, I am currently having toubles with it in another work. So it might not work out. 

Please feel free to comment on this if you have any advice or questions

**Comment by johnagl** [comment]
The reason I was suggesting to query course in add courses section is because of the below screenshot. **We want to display as much info about the course as early as possible** , since our **user research indicated that one of the biggest issues with SSC is that students have to navigate to multiple pages to find information**. In the future, this might even display Rate my professor data. We dont have this information without querying the db. Also, if they type the course wrong, we can return an error saying that course doesnt exist, again, we need to query the db to check if this course exists. I was also thinking if you click into selected courses, we should somehow see details of the course as well. 

If the user adds multiple courses, such as CPSC 100, CPSC 330, CPSC 566 but CPSC 566 doesn't exist, they will have to go back from restrictions page and fix it, I thought maybe querying one at a time is easier than having to go back and edit. But suggestions are welcome, @nico-zhu  and @sarahdang what do you think?

@aldy97 I like the idea of querying ALL courses like in your screenshot the only issue with this is that currently we have a course section table with 19k rows LOL.

![course selection](https://user-images.githubusercontent.com/42220961/98454026-8d61ee00-2114-11eb-9e0a-4847fbb6724e.png)

**Comment by resurl** [comment]
@johnagl i know that @yehee took out the CourseCode table for simplicity's sake, but would this be a good reason to include it? i think there's something like ~6k actual courses if i remember correctly and that's still a heck ton but it sounds a little better than querying 19k sections that we don't really need LOL

i think at this point in the process, i see users wanting to add only the course that they want and not any specific section (which has the professor name). if we go with querying all of the course codes, the front end people might also have an easier time implementing the autocompletion you mentioned because of [this material ui thing](https://material-ui.com/components/autocomplete/) i saw. not sure though!

**Comment by aldy97** [comment]
@johnagl Sorry, I misunderstood what you meant by 'query the db' during the meeting. @resurreccionl you are absolutely right. Material UI does provide auto-complete input box but requires all candidate courses to be loaded before hand, thus we could query all courses (not sections, so I guess it will be much less than 19k or 6k rows) when the component is mounted (talking about this lifecycle-wise, during **componentDidMount**). With this being implemented, users would know some course does not exist when they see no suggestion pop up before they type out the whole course name and course number. Once a course has been selected, then we query the db for that specific course info and render it. After 'add course' button is clicked, update redux (which should be synchronous)

**Comment by johnagl** [comment]
@resurreccionl CourseCode table might be useful.... @aldy97 the only issue with this is that the previous CourseCode table only included Course department and Course number, and 0 details about the actual course - so we would end up querying 6k rows with only CourseDept and CourseNum, then later when we want to get more course details, we would have to query again... :( I didnt realize we would have to query the DB so much. @aldy97 I think for the MVP, lets not worry too much about efficiency. We can worry about making db read/writes more efficient later.

**Comment by johnagl** [comment]
Closing this issue for now, but I think we should open an issue for a drop down that shows up of valid courses in the input box, makes the user experience much better.
