### ISSUE TITLE
Added Selected Term into Redux

### ISSUE THREAD

**Issue by aldy97** [ubclaunchpad/life-at-ubc#78]
Before users enter the phase of course selection, they need to select school year (which we havent discussed yet...?) and term. Thus we need to update redux on term selected, and let course component have easy access to that. By adding the selected term, the component will be able to remember that after its re-mounted again.

**Comment by johnagl** [comment]
You're right. I realize that we aren't scraping any information about the `year`, unless I'm mistaken. We currently only store `term` information (1, 2, 1-2). Additionally, we're only storing for the current year. We'll have to make tweaks to the scraper again :D. In the meantime @aldy97 we don't have to worry about this for the MVP since we only have the current year at the moment , users don't have a choice. We can make another issue for this :) @resurreccionl .

For now, maybe only have 1 choice in the Year dropdown (the current year).

**Comment by resurl** [comment]
sorry, i just moved so i wont be able to push anything until my wifi is set up on tuesday 🙃 

i think we might've discussed this really briefly before, if you're talking about adding something like 2020WT, 2020ST, etc., but will the user need to choose a school year? 

since only one course schedule is relevant at any given time (i think lol) and each year has a ton of courses/sections, it feels a little unnecessary to let them have the option

**Comment by aldy97** [comment]
Okay, I think it makes more sense leaving years options out. So we are only allwoing users to choose from ['term 1', 'term 2', 'term 1 to term 2']? How about summer?

**Comment by resurl** [comment]
@aldy97 yes @ your first question, and for the second, summer has its own course schedule, so hypothetically the scraper would run and replace the winter term schedule with the summer one, whenever it gets made, so the database would get updated with the new course info! i think that's how it would work.

**Comment by johnagl** [comment]
I'm not sure about term1-term2. Right now we are showing 1 schedule for 1 term (not 2 terms). For MVP lets set it to only term 1 or term 2.

**Comment by aldy97** [comment]
@johnagl Okay, I will remove year selection then.

**Comment by johnagl** [comment]
Closing this now that it's finished.
