### ISSUE TITLE
Display generated course schedules (lectures) on schedule grid

### ISSUE THREAD

**Issue by johnagl** [ubclaunchpad/life-at-ubc#81]
Currently, the ScheduleGrid component has hard coded courses as shown below. Now that we have a working course scheduler algorithm - we can use that to generate schedules based on user input courses.  The current ScheduleGrid component will require some changes. We'll have to call the courseScheduler algorithm passing in courseSections from the Redux store and then display the results.

![Lectures](https://user-images.githubusercontent.com/42220961/99497008-1b668180-292a-11eb-9b34-6794b8b8467e.png)

**Comment by johnagl** [comment]
Current ScheduleGrid component also needs some polish in terms of styling to make it look more like the designs, but this isn't required for MVP.

**Comment by johnagl** [comment]
So after looking at ScheduleGrid component again, it looks like if a course is from 8-9:30, its taking up 3 separate rows and being listed 3 separate times as shown above (eg. MATH 307). We want it to be showing up as 1 block. I'm not sure if Material UI's grid component allows that, but I asked @danielchen-pyc to look into it. 

If Material UI doesnt work out we might actually have to create our own custom component (better for customizability, but more initial work up front).

**Comment by danielchen-pyc** [comment]
So basically, each half an hour session will take up one cell (row) of the datagrid, one hour will take up two cells/rows, etc. Since it is printing the course name in every cell the course occupies, we need to find a way to display it only once, preferably at the centre. There are multiple ways to do this,
- For odd # of rows, we just display at the centre-most cell (this should be really simple to implement. For even # of rows, we merge the cells and display it at the centre. This requires Material UI's row spanning feature. 
- We can simply use different colours to indicate different courses, and the boundaries between courses will be obvious. We can, then, display the course name at the first cell only.
- Or we can just display the course name at the n/2 cell for even n's. 

To span the rows between multiple columns, we need the row spanning feature in Material UI. Unfortunately, they are still working on this add-on feature. 

https://material-ui.com/components/data-grid/rows/#row-spanning

**Comment by danielchen-pyc** [comment]
There are some other grid components we can use:
- [Ant Design](https://ant.design/components/table/#components-table-demo-colspan-rowspan)
- [ej2 Syncfusion](https://ej2.syncfusion.com/react/demos/#/material/grid/row-spanning)
- [ag-grid](https://ag-grid.com/javascript-grid-row-spanning/)

**Comment by johnagl** [comment]
> There are some other grid components we can use:
> 
> * [Ant Design](https://ant.design/components/table/#components-table-demo-colspan-rowspan)
> * [ej2 Syncfusion](https://ej2.syncfusion.com/react/demos/#/material/grid/row-spanning)
> * [ag-grid](https://ag-grid.com/javascript-grid-row-spanning/)

We should just write our own custom one tbh. Lol

**Comment by johnagl** [comment]
I started playing around with raw html table/grid stuff on https://github.com/ubclaunchpad/life-at-ubc/compare/justForFun , sort of laid out how I think it will work if we don't use a table/grid library.

Also spent some time looking for decent grid/table libraries (ones with rowspan) , haven't been able to find any yet....

**Comment by johnagl** [comment]
> > There are some other grid components we can use:
> > 
> > * [Ant Design](https://ant.design/components/table/#components-table-demo-colspan-rowspan)
> > * [ej2 Syncfusion](https://ej2.syncfusion.com/react/demos/#/material/grid/row-spanning)
> > * [ag-grid](https://ag-grid.com/javascript-grid-row-spanning/)
> 
> We should just write our own custom one tbh. Lol

If there's 1 with rowspan, that would fix our problem hahaha. Ive seen some popular ones on npm but havent seen them having rowspan feature :(.
